name: Shell Commands workflow

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: run python commands
        run: |
          import platform
          print (platform.processor())
        shell: python
